content_generator:
  llm_model: "gemini-1.5-pro-latest"
  meta_llm_model: "gemini-1.5-pro-latest"
  max_output_tokens: 8192

research:
  llm_model: "deepseek-chat"
  temperature: 0
topic:
  llm_model: "deepseek-chat"
  temperature: 0

content_extractor:
  youtube_url_patterns:
    - "youtube.com"
    - "youtu.be"
  bilibili_url_patterns:
    - "bilibili.com"

youtube_transcriber:
  remove_phrases:
    - "[music]"

bilibili_transcriber:
  cookies: "./data/cookies"

website_extractor:
  jina_api_url: "https://r.jina.ai"
  markdown_cleaning:
    remove_patterns:
      - '\[.*?\]' # Remove square brackets and their contents
      - '\(.*?\)' # Remove parentheses and their contents
      - '^\s*[-*]\s' # Remove list item markers
      - '^\s*\d+\.\s' # Remove numbered list markers
      - '^\s*#+' # Remove markdown headers
      - '!\[.*?\]\(.*?\)'
      - '\[([^\]]+)\]\([^\)]+\)'
      - 'https?://\S+|www\.\S+'
  unwanted_tags:
    - "script"
    - "style"
    - "nav"
    - "footer"
    - "header"
    - "aside"
    - "noscript"
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
  timeout: 10 # Request timeout in seconds

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
