conversation_style:
  - "engaging"
  - "fast-paced"
  - "enthusiastic"
roles_person1: "main summarizer"
roles_person2: "questioner/clarifier"
dialogue_structure:
  - "Introduction"
  - "Main Content Summary"
  - "Conclusion"
podcast_name: "PODCASTIFY"
podcast_tagline: "Your Personal Generative AI Podcast"
output_language: "Chinese"
engagement_techniques:
  - "rhetorical questions"
  - "anecdotes"
  - "analogies"
  - "humor"
creativity: 1
user_instructions: ""
max_num_chunks: 8 # maximum number of rounds of discussions in longform
min_chunk_size: 600 # minimum number of characters to generate a round of discussion in longform

text_to_speech:
  default_tts_model: "openai"
  output_directories:
    transcripts: "./data/transcripts"
    audio: "./data/audio"
  fish:
    default_voices:
      question: "7f92f8afb8ec43bf81429cc1c9199cb1"
      answer: "e80ea225770f42f79d50aa98be3cedfc"
  elevenlabs:
    default_voices:
      question: "Chris"
      answer: "Jessica"
    model: "eleven_multilingual_v2"
  openai:
    default_voices:
      question: "echo"
      answer: "shimmer"
    model: "tts-1"
  edge:
    default_voices:
      question: "zh-CN-XiaomengNeural"
      answer: "zh-CN-XiaoshuangNeural"
  gemini:
    default_voices:
      question: "en-US-Journey-D"
      answer: "en-US-Journey-O"
  geminimulti:
    default_voices:
      question: "R"
      answer: "S"
      model: "en-US-Studio-MultiSpeaker"
  audio_format: "mp3"
  temp_audio_dir: "data/audio/tmp/"
  ending_message: "Bye Bye!"
